[chore] Reject duplicate deposit requests when first one already accepted | confirmed | failed
stacks-sbtc/sbtc pull request #1179
Opened 2024-12-23 14:04 UTC by MCJOHN974

## Description

Closes: #1161

## Changes

Now `create_deposit` requests returns 409 (Conflict) if we already have same deposit accepted

## Testing Information

Added integration test for this.

Locally I run it the following way:
```
 docker compose -f docker/docker-compose.test.yml build   // rebuild emily
 docker compose --file docker/docker-compose.test.yml up.  // start emily
 // open new terminal
 cargo test --package emily-handler --test integration -- deposit::overwrite_deposit --exact --show-output --ignored // run the test
 ```

## Checklist:

- [x] I have performed a self-review of my code
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

2025-01-07 10:41 UTC, Jiloc reviewed
Welcome to the Emily side of things @MCJOHN974 ! I left a few comments about changes required to handle duplicates deposits in all statuses

2025-01-07 10:41 UTC, Jiloc commented on emily/handler/src/api/handlers/deposit.rs
> +        }
I am not 100% sure, but I believe the duplicate check should go after the reorg check below
```
        let api_state = accessors::get_api_state(&context).await?;
        api_state.error_if_reorganizing()?;
```
@AshtonStephens what do you think?

2025-01-07 10:41 UTC, Jiloc commented on emily/handler/src/api/handlers/deposit.rs
> +            accessors::get_deposit_entries(&context, &Status::Accepted, None, None).await?;
I think we should prevent deposits from being overridden in any state.

One case we encountered was when a Pending deposit was created multiple times. Each time it was overridden, a new higher stacks_block_height was linked to the deposit. Sometimes the new stacks_block_height was higher than the block_height in which the deposit would be marked as Approved or Completed by the signers, and it would cause Emily to reject the updates.

2025-01-07 10:41 UTC, Jiloc commented on emily/handler/src/api/handlers/deposit.rs
> +                let responce = json(&serde_json::json!({
typo: responce -> response

2025-01-07 10:41 UTC, Jiloc commented on emily/handler/src/api/handlers/deposit.rs
> +            accessors::get_deposit_entries(&context, &Status::Accepted, None, None).await?;
A possible solution could be to use the function `accessors::get_deposit_entry` to get the specific entry whatever its status, instead of iterating all entries

2025-01-07 10:58 UTC, matteojug requested changes

2025-01-07 10:58 UTC, matteojug commented on emily/handler/src/api/handlers/deposit.rs
> +            accessors::get_deposit_entries(&context, &Status::Accepted, None, None).await?;
You can use `get_deposit_entry` to directly get the deposit

2025-01-07 10:58 UTC, matteojug commented on emily/handler/src/api/handlers/deposit.rs
> +                }));
Looking around we return `Error` directly (`Error::Conflict` here) and let the `impl Error` handle the required serialization.

2025-01-07 10:58 UTC, matteojug commented on emily/handler/src/api/handlers/deposit.rs
> +        // Create deposit.
nit: the previous `// Set variables.` seems fine here, why the change?

2025-01-07 10:58 UTC, matteojug commented on emily/handler/src/api/handlers/deposit.rs
> +        // Reject dups.
nit: expand a bit, since it's not all the duplicates

2025-01-07 10:58 UTC, matteojug commented on emily/handler/tests/integration/deposit.rs
> +async fn overwrite_deposit() {
Once we add the reject also for the other states, can we add test cases for those as well? Other than the `Fullfilment`, everything else can be the same I guess

2025-01-07 11:04 UTC, matteojug commented on emily/handler/src/api/handlers/deposit.rs
> +                && deposit.status == Status::Accepted
(answering to your Q) yeah we probably want to reject also for `Confirmed` and `Failed`. Not 100% sure about `Reprocessing` ones, but since we are not using that state at the moment let's not include it. @Jiloc WDYT?

2025-01-07 11:22 UTC, Jiloc commented on emily/handler/src/api/handlers/deposit.rs
> +            accessors::get_deposit_entries(&context, &Status::Accepted, None, None).await?;
Ok, sorry for the confusion then! I didn't know we wanted to still have room to modify a pending deposit for possible malformed requests. 

The thing I would suggest is:
- if the request exists and is not in Pending then reject
- if the request exists and it is in Pending, override it, but preserve its original `stacks_block_height` and `stacks_block_hash` https://github.com/stacks-network/sbtc/blob/viktar/emily-returns-error-on-cloned-tx/emily/handler/src/api/handlers/deposit.rs#L238-L239

2025-01-07 11:30 UTC, Jiloc commented on emily/handler/src/api/handlers/deposit.rs
> +                && deposit.status == Status::Accepted
The Reprocessing state is not currently in use. Everything that we were previously moving to Reprocessing is now moved back to Pending for simplicity. https://github.com/stacks-network/sbtc/pull/1074 

I am not sure if we'll ever re-introduce it. Given that we want to be able to modify pending deposits, the most correct approach would be to keep it overridable like the Pending state..

2025-01-07 11:38 UTC, Jiloc commented on emily/handler/src/api/handlers/deposit.rs
> +        }
This is the only official doc i found about it https://docs.google.com/document/d/13AN9GdLfPYKKPkeHNU4niq_CyJCDxFR7DGBLzLc5gxU/edit?tab=t.0#heading=h.9q7n8dly2bue

But in short - when Emily receives a conflicting chainstate update from the sidecar (e.g., a Stacks chainstate update for a block height Emily has already recorded, but with a different block hash), Emily interprets this as a chain reorganization. As a result, any updates received after that block are deemed invalid. Emily then deletes all deposit and withdrawal updates recorded after the block_height of the new block. (only the updates, the deposits/withdrawal records will still be in Dynamo)

2025-01-08 13:16 UTC, Jiloc commented on emily/handler/src/api/handlers/deposit.rs
> +            accessors::get_deposit_entries(&context, &Status::Accepted, None, None).await?;
Great, looks good now! We just need to address the second part of the request: if the deposit already exists and is in a pending or reprocessing state, ensure that the values for [stacks_block_height and stacks_block_hash](https://github.com/stacks-network/sbtc/blob/viktar/emily-returns-error-on-cloned-tx/emily/handler/src/api/handlers/deposit.rs#L236-L237) are set as they are in the existing deposit

2025-01-08 14:05 UTC, matteojug commented on emily/handler/src/api/handlers/deposit.rs
> +        .await;
As `get_deposit_entry` can fail for different reasons, we should propagate the error if it's not `Error::NotFound`, otherwise in case of unrelated errors (eg, dynamodb throttling) we may skip the check.

2025-01-08 14:08 UTC, matteojug commented on emily/handler/tests/integration/deposit.rs
> +    }
We can use `test_case` for this to improve readability (both of code and test results), eg https://github.com/stacks-network/sbtc/blob/83b316c5d26a3434a1b53d558bc7f899ce6c03f2/emily/handler/src/database/entries/deposit.rs#L651-L657

2025-01-08 18:17 UTC, matteojug approved these changes

2025-01-08 18:17 UTC, matteojug commented on emily/handler/tests/integration/deposit.rs
> +use test_case::test_case;
nit: move up

2025-01-08 18:17 UTC, matteojug commented on emily/handler/tests/integration/deposit.rs
> +            .expect("Received an error after making a valid get deposit api call.");
nit: wrong err message, also we could simplify this block by `assert_eq` that `create_deposit(...).await.is_err()` matches `should_reject`.
Note that we already have the info related to which test case is running (eg, `emily-handler::integration deposit::overwrite_deposit::should_not_reject_pending_duplicate`), so we would still have everything we need to find the failing case.

2025-01-09 09:18 UTC, merged